name: Run Unit Test via Pytest

on:
    push:
        paths:
            - "projects/NatLang2Latex/**/*"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["^3.10"]

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  pip install pytest
                  pip install pytest-cov
            # run coverage once we have real tests
            # - name: Test with pytest
            #   run: |
            #       coverage run -m pytest projects/NatLang2Latex -v -s
            # - name: Generate Coverage Report
            #   run: |
            #       coverage report projects/NatLang2Latex -m
            - name: Test with pytest
              run: |
                  pytest projects/NatLang2Latex -v -s
